### ISSUE TITLE
AttributeError: 'Call' object has no attribute 'id'

### ISSUE THREAD

**Issue by christian-oleary** [cleancodecommunity/SCAIT#1]
The main() function in main.py runs in to an AttributeError when running on certain Python files

## Expected Behavior
(printed log)

## Current Behavior
```
Traceback (most recent call last):
  File "C:\sw\SCAIT\src\main\java\python_control\main.py", line 440, in <module>
    main()
  File "C:\sw\SCAIT\src\main\java\python_control\main.py", line 391, in main
    getRoot(nn, Roote,  project)
  File "C:\sw\SCAIT\src\main\java\python_control\main.py", line 350, in getRoot
    getFunctionDef(subNode, claz, project)
  File "C:\sw\SCAIT\src\main\java\python_control\main.py", line 66, in getFunctionDef     
    method = methodEntity.methodEntity(node.name, allArgs, project, isStatic(node),claz)  
  File "C:\sw\SCAIT\src\main\java\python_control\main.py", line 193, in isStatic
    if node.decorator_list[0].id == "staticmethod":
AttributeError: 'Call' object has no attribute 'id'
```

## Steps to Reproduce
It is now easier to reproduce with the test scripts:
```
pip install ./tests/python/requirements.txt
sh ./tests/python/pull_repos.sh
python -m pytest tests/python/test_parsing.py
```

(Previous)
~~1. git clone https://github.com/keras-team/autokeras.git~~
~~2. Comment out lines 25-29 and 431 in src/main/java/python_control/main.py which contain hardcoded lines~~
~~3. Add the following code to src/main/java/python_control/main.py:~~

~~import os
for subdir, dirs, files in os.walk('./autokeras'):
    for f in files:
        if len(f) > 3 and f[-3:] == '.py':
            fileName = os.path.join(subdir, f)
            with open(fileName, 'r') as file:
                data = file.read()
            main()~~

~~4. Run ```python src/main/java/python_control/main.py```~~

**Comment by christian-oleary** [comment]
~~This issue also occurs with the SCAIT code itself using:~~

~~import os
for subdir, dirs, files in os.walk('.'):
    for f in files:
        if len(f) > 3 and f[-3:] == '.py':
            fileName = os.path.join(subdir, f)
            print(fileName)
            with open(fileName, 'r') as file:
                data = file.read()
            main()~~

(Just use test scripts provided in ./tests/python currently available on python_testing branch)

Hi @farshad1361, I made it easier to test the code using the test scripts in ./tests/python

**Comment by cleancodecommunity** [comment]
Hi @christian-oleary the issue is now resolved. The problem happened in a function that checks whether a method is static. Initially, the parser would look at the decorators of the functions/methods, e.g., @static, etc... however, the decorator of one of the functions has a different format and mimics the function call format. Therefore, the parser sees that as a Function Call. I just add a simple if statement and now it should work... Since this function only take care of static methods, there is no need to be worried about other decorators.

**Comment by christian-oleary** [comment]
Hi @cleancodecommunity, that works for me. I will close the issue and test with more repositories
